# 
# Synthesis run script generated by Vivado
# 

namespace eval rt {
    variable rc
}
set rt::rc [catch {
  uplevel #0 {
    set ::env(BUILTIN_SYNTH) true
    source $::env(HRT_TCL_PATH)/rtSynthPrep.tcl
    rt::HARTNDb_startJobStats
    set rt::cmdEcho 0
    rt::set_parameter writeXmsg true
    rt::set_parameter enableParallelHelperSpawn true
    set ::env(RT_TMP) "./.Xil/Vivado-212002-ajit-System-Product-Name/realtime/tmp"
    if { [ info exists ::env(RT_TMP) ] } {
      file mkdir $::env(RT_TMP)
    }

    rt::delete_design

    set rt::partid xc7k325tffg900-2

    set rt::multiChipSynthesisFlow false
    source $::env(SYNTH_COMMON)/common_vhdl.tcl
    set rt::defaultWorkLibName xil_defaultlib

    # Skipping read_* RTL commands because this is post-elab optimize flow
    set rt::useElabCache true
    if {$rt::useElabCache == false} {
      rt::read_verilog -sv -include {
    /home/aiml/Desktop/IITB_AI_ML/KC705_WITH_DRAM/UNET/ip/ila/ila_0/hdl/verilog
    /home/aiml/Desktop/IITB_AI_ML/KC705_WITH_DRAM/UNET/ip/clk_wiz_0
  } {
      /home/aiml/my-xil-dir/Vivado/2017.1/data/ip/xpm/xpm_cdc/hdl/xpm_cdc.sv
      /home/aiml/my-xil-dir/Vivado/2017.1/data/ip/xpm/xpm_memory/hdl/xpm_memory.sv
    }
      rt::read_verilog -include {
    /home/aiml/Desktop/IITB_AI_ML/KC705_WITH_DRAM/UNET/ip/ila/ila_0/hdl/verilog
    /home/aiml/Desktop/IITB_AI_ML/KC705_WITH_DRAM/UNET/ip/clk_wiz_0
  } {
      ./.Xil/Vivado-212002-ajit-System-Product-Name/realtime/mig_7series_0_stub.v
      ./.Xil/Vivado-212002-ajit-System-Product-Name/realtime/ila_0_stub.v
      ./.Xil/Vivado-212002-ajit-System-Product-Name/realtime/clk_wiz_0_stub.v
      ./.Xil/Vivado-212002-ajit-System-Product-Name/realtime/fifo_generator_1_stub.v
      ./.Xil/Vivado-212002-ajit-System-Product-Name/realtime/fifo_generator_2_stub.v
      ./.Xil/Vivado-212002-ajit-System-Product-Name/realtime/fifo_generator_3_stub.v
      ./.Xil/Vivado-212002-ajit-System-Product-Name/realtime/fifo_generator_4_stub.v
      /home/aiml/Desktop/IITB_AI_ML/KC705_WITH_DRAM/UNET/verilog_libs/ACB_to_UI_EA.v
    }
      rt::read_vhdl -lib ahir /home/aiml/Desktop/IITB_AI_ML/KC705_WITH_DRAM/UNET/vhdl_libs/ahir.vhdl
      rt::read_vhdl -lib ahir_ieee_proposed /home/aiml/Desktop/IITB_AI_ML/KC705_WITH_DRAM/UNET/vhdl_libs/aHiR_ieee_proposed.vhdl
      rt::read_vhdl -lib AjitCustom /home/aiml/Desktop/IITB_AI_ML/KC705_WITH_DRAM/UNET/vhdl_libs/AjitCustom.vhdl
      rt::read_vhdl -lib simpleUartLib /home/aiml/Desktop/IITB_AI_ML/KC705_WITH_DRAM/UNET/vhdl_libs/simpleUartLib.vhdl
      rt::read_vhdl -lib GenericCoreAddonLib /home/aiml/Desktop/IITB_AI_ML/KC705_WITH_DRAM/UNET/vhdl_libs/GenericCoreAddOnLib.vhdl
      rt::read_vhdl -lib GenericGlueStuff /home/aiml/Desktop/IITB_AI_ML/KC705_WITH_DRAM/UNET/vhdl_libs/GenericGlueStuff.vhdl
      rt::read_vhdl -lib GlueModules /home/aiml/Desktop/IITB_AI_ML/KC705_WITH_DRAM/UNET/vhdl_libs/GlueModules.vhdl
      rt::read_vhdl -lib AxiBridgeLib /home/aiml/Desktop/IITB_AI_ML/KC705_WITH_DRAM/UNET/vhdl_libs/AxiBridgeLib.vhdl
      rt::read_vhdl -lib work {
      /home/aiml/Desktop/IITB_AI_ML/KC705_WITH_DRAM/UNET/ahir/ahir_system_global_package.vhdl
      /home/aiml/Desktop/IITB_AI_ML/KC705_WITH_DRAM/UNET/ahir/ahir_system.vhdl
      /home/aiml/Desktop/IITB_AI_ML/KC705_WITH_DRAM/UNET/vhdl/toplevel.vhdl
    }
      rt::read_vhdl -lib xpm /home/aiml/my-xil-dir/Vivado/2017.1/data/ip/xpm/xpm_VCOMP.vhd
      rt::filesetChecksum
    }
    rt::set_parameter usePostFindUniquification true
    set rt::SDCFileList ./.Xil/Vivado-212002-ajit-System-Product-Name/realtime/dram_spi_wrapper_ui64_synth.xdc
    rt::sdcChecksum
    set rt::top dram_spi_wrapper_ui64
    set rt::reportTiming false
    rt::set_parameter elaborateOnly false
    rt::set_parameter elaborateRtl false
    rt::set_parameter eliminateRedundantBitOperator true
    rt::set_parameter writeBlackboxInterface true
    rt::set_parameter inferFsm false
    rt::set_parameter ramStyle auto
    rt::set_parameter merge_flipflops true
# MODE: 
    rt::set_parameter webTalkPath {./.Xil/Vivado-212002-ajit-System-Product-Name/wt}
    rt::set_parameter enableSplitFlowPath "./.Xil/Vivado-212002-ajit-System-Product-Name/"
    set ok_to_delete_rt_tmp true 
    if { [rt::get_parameter parallelDebug] } { 
       set ok_to_delete_rt_tmp false 
    } 
    if {$rt::useElabCache == false} {
        set oldMIITMVal [rt::get_parameter maxInputIncreaseToMerge]; rt::set_parameter maxInputIncreaseToMerge 1000
        set oldCDPCRL [rt::get_parameter createDfgPartConstrRecurLimit]; rt::set_parameter createDfgPartConstrRecurLimit 1
      rt::run_synthesis -module $rt::top
        rt::set_parameter maxInputIncreaseToMerge $oldMIITMVal
        rt::set_parameter createDfgPartConstrRecurLimit $oldCDPCRL
    }

    set rt::flowresult [ source $::env(SYNTH_COMMON)/flow.tcl ]
    rt::HARTNDb_stopJobStats
    rt::HARTNDb_reportJobStats "Synthesis Optimization Runtime"
    rt::HARTNDb_stopSystemStats
    if { $rt::flowresult == 1 } { return -code error }

    if { [ info exists ::env(RT_TMP) ] } {
      if { [info exists ok_to_delete_rt_tmp] && $ok_to_delete_rt_tmp } { 
        file delete -force $::env(RT_TMP)
      }
    }


  set hsKey [rt::get_parameter helper_shm_key] 
  if { $hsKey != "" && [info exists ::env(BUILTIN_SYNTH)] && [rt::get_parameter enableParallelHelperSpawn] && [info exists rt::doParallel] && $rt::doParallel} { 
     $rt::db killSynthHelper $hsKey
  } 
  rt::set_parameter helper_shm_key "" 
    source $::env(HRT_TCL_PATH)/rtSynthCleanup.tcl
  } ; #end uplevel
} rt::result]

if { $rt::rc } {
  $rt::db resetHdlParse
  set hsKey [rt::get_parameter helper_shm_key] 
  if { $hsKey != "" && [info exists ::env(BUILTIN_SYNTH)] && [rt::get_parameter enableParallelHelperSpawn] && [info exists rt::doParallel] && $rt::doParallel} { 
     $rt::db killSynthHelper $hsKey
  } 
  source $::env(HRT_TCL_PATH)/rtSynthCleanup.tcl
  return -code "error" $rt::result
}
