#include <stdlib.h>
#include <stdint.h>
#include <stdio.h>
#include <string.h>
#include <Pipes.h>
#include <SocketLib.h>
void conv2D();
void convCore1();
void convCore2();
void convCore3();
void convCore4();
void convCore5();
void getInput();
void global_storage_initializer_();
void progx_xoptx_xo_storage_initializer_();
void sendOutput();
uint64_t timer();
void timerDaemon();
